spring:
  application:
    name: task-system
  datasource:
    url: jdbc:mysql://localhost:3306/task-system
    username: root
    password: 121235
    driver-class-name: com.mysql.cj.jdbc.Driver

# MyBatis 配置打印 SQL 的日志
logging:
  level:
    com.jacolp.task_system: trace

# 启用 MyBatis 驼峰命名
mybatis:
  configuration:
    map-underscore-to-camel-case: true

# AI 配置
ai:
  deepseek:
    api-key: sk-9fef969fa05a4e60812152c8709fa6ff
    api-url: https://api.deepseek.com/chat/completions
    model: deepseek-chat
